# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Seeds from the Apple of Discord
email: malumdiscordiae@mailbox.org
description: > # this means to ignore newlines until "baseurl:"
  Johanna Appel's musings about the world, science & technology,
  programming, languages, music, art, learning and absurdities.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://malumdiscordi.ae" # the base hostname & protocol for your site
twitter_username: ephe_meral
github_username:  ephe-meral

excerpt_separator: <!--more-->

# Build settings
markdown: kramdown

gems:
  - octopress-codeblock
  - octopress-codefence
  - octopress-image-tag
  - octopress-quote-tag
  - octopress-solarized
  - octopress-social
  - octopress-linkblog
  - octopress-filter-tag
  - octopress-filters
  - octopress-comment-tag
  - jekyll-sitemap
#  - octopress-genesis-theme
